### PR TITLE
Executed elm-upgrade to support Elm 0.18

### PR DESCRIPTION
**Pull request by FrankRaiser**

### CODE REVIEW

**Comment by nickmiller-wf** [comment]
Should this also bump the package version to 2.0.0?

**Comment by ghost** [comment]
Yes, think so, but I currently don't have the time to look in to it. Will try next week.

**Comment by ghost** [comment]
On second thought I don't think so, because the API stays the same.

**Comment by nickmiller-wf** [comment]
@rmies Hmm good point, but I'm not sure. If a consumer were to remain on elm 0.17 and pull the latest published version of this package, they couldn't satisfy the lower-bound of `>= 0.18` in the `elm-package.json`

**Comment by ghost** [comment]
Yes, they should stick with the current version.

**Comment by nickmiller-wf** [comment]
I'd be interested to see what the elm package manager reports. I'm fairly certain it won't let you publish this without a version bump to `2.0.0`, but I could be wrong.

**Comment by ghost** [comment]
We'll just have to wait and see :-)

**Comment by FrankRaiser** [comment]
I'm pretty new to Elm, so I'm not sure I did this right. But apparently it is not considered a major change by elm-package:

```
$ elm-package diff
Comparing truqu/elm-base64 1.0.4 to local changes...
This is a PATCH change.
```

I do see the problem with 0.17 users though and I agree that a major bump would be more appropriate. Let me know if I should add it to the PR or whether you just do it along with the merge.

**Comment by ghost** [comment]
No problem, I'll do it along with the merge; thanks!

**Pull request merged**
