### PR TITLE
Upgrade v0.16.0

### PR DESCRIPTION
**Pull request by amitaibu**
Still untested. In order to avoid the blocking module (TheSeamau5 seems to be M.I.A :/) I've added Shrink.elm directly here. Ugly, but ugly :)

### CODE REVIEW

**Comment by amitaibu** [comment]
I have tested this along with a port of [hedley](https://github.com/Gizra/elm-hedley/pull/117) to v16 and it seems to work.

**Comment by ghost** [comment]
Merged, thanks!

**Comment by amitaibu** [comment]
Thanks! Are you going to publish this?

**Comment by ghost** [comment]
Yes, but I want to do some cleaning up first.

**Pull request merged**
